---

- name: Baixando o pacote do Emby
  get_url:
   url: "https://github.com/MediaBrowser/Emby.Releases/releases/download/{{ emby_version }}/emby-server-rpm_{{ emby_version }}_x86_64.rpm"
   dest: "/tmp/emby-server-rpm_{{ emby_version }}_x86_64.rpm"
   validate_certs: no
  tags:
   - emby

- name: Instalando o pacote do Emby
  dnf:
    name: "/tmp/emby-server-rpm_{{ emby_version }}_x86_64.rpm"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - emby